### PR TITLE
sync openwhisk catalog docs Fixes #261 #262 #263

### LINKED ISSUE #261: openwhisk cloudant trigger example use includeDocs instead of includeDoc
In [openwhisk/openwhisk_catalog.md](https://github.com/IBM-Bluemix/docs/blob/master/openwhisk/openwhisk_catalog.md)

The following example:
```
wsk trigger create myCloudantTrigger --feed /myNamespace/myCloudant/changes --param dbname testdb --param includeDocs true
```

```
Otherwise, if `includeDocs` is false, the events include the following parameters:
```
The parameter name is includeDoc not includeDocs

### PR DESCRIPTION
**Pull request by csantanapr**
Fixes #261 #262 #263

### CODE REVIEW

**Comment by csantanapr** [comment]
@sefuhrer Can you merge this please?

**Comment by sefuhrer** [comment]
@csantanapr I know we spoke on slack, before I accept, I want to ensure the Cron syntax is correct. We pulled the example previously.

**Comment by rabbah** [comment]
@csantanapr suggest we have a unit test for this example if we don't already.

**Comment by csantanapr** [comment]
@sefuhrer @rabbah I review the section and tried it out and found a problem.
https://github.com/openwhisk/openwhisk/issues/496

I will update this PR with the corrections

**Comment by rabbah** [comment]
thanks - let's also make sure the examples are tested ;)

**Comment by csantanapr** [comment]
@rabbah I will open an issue to check if there are unit tests that cover the example in the docs

**Comment by csantanapr** [comment]
@sefuhrer I updated the alarm examples, can you merge when you have a chance.

**Pull request merged**
