### PR TITLE
New Liberty features table and description

### PR DESCRIPTION
**Pull request by bwoolf1**
Same list of Liberty features, but described and formatted to show which features correspond to which convenience features like javaee-7.0. This comes from the article "Java EE, the next inception: Install a local Java EE development environment for Bluemix" (http://www.ibm.com/developerworks/websphere/library/techarticles/1602_woolf-trs/1602_woolf3.html#sec2b).

### CODE REVIEW

**Comment by jgawor** [comment]
I don't think this particular table format makes sense for the Bluemix documentation. I think a user probably just wants to know what's supported and what's enabled by default - in other words, doesn't really care if it is a ee 6 web profile or ee 7 full profile feature. But I do agree that the list of feature table is a bit log and it probably makes sense to separate it into smaller tables - e.g. one for ee 6 features, one for ee 7 features, one for other features, etc.

**Comment by bwoolf1** [comment]
Here's the problem: How are Liberty and Bluemix users supposed to know this stuff? How should they know what build of Liberty to download, what convenience feature to enable, such as in the server config they push to Bluemix? I've not found a table like this. Furthermore, a Liberty-only table would not explain what features are available in Bluemix. We could have two separate tables, one in the Liberty docs and one in the Bluemix docs, but it's difficult to find documentation in several different places and consolidate it; users will find it easier to read a summary in one place (such as this table).

**Comment by jgawor** [comment]
[This table](https://www.ibm.com/support/knowledgecenter/SSEQTP_8.5.5/com.ibm.websphere.wlp.doc/ae/rwlp_feat.html) shows a list of features, grouped by type and identifies which WebSphere edition supports them. In the Bluemix documentation, we can add a link to that page but there is no point of showing in a verbose way that for example `cdi-1.2` is a EE 7 feature and not EE 6 feature. We just need to show which features are supported in Bluemix. We can still group things like on [this page](http://www.ibm.com/support/knowledgecenter/was_beta_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_feat.html) but the long table format is unnecessary.

**Comment by bwoolf1** [comment]
The [WAS 8.5.5 Liberty features](https://www.ibm.com/support/knowledgecenter/SSEQTP_8.5.5/com.ibm.websphere.wlp.doc/ae/rwlp_feat.html) table includes columns for Liberty Core and WAS ND. How do I use those in Bluemix? The [WAS Beta Liberty features](http://www.ibm.com/support/knowledgecenter/was_beta_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_feat.html) table lists the Java EE 6 Full Platform features and others like serverStatus-1.0, passwordUtilities-1.0, and dynamicRouting-1.0. How do I use those in Bluemix?

The docs for Liberty middleware do not explain Liberty in Bluemix (especially the Liberty for Java buildpack) very well. At the very least, we should work with the Liberty documentation writers to explain Liberty better, including how it works in Bluemix.

But better yet, the Bluemix documentation should explain to Bluemix users how things work in Bluemix. We want to make Bluemix easier to understand, not tell users to go read other documentation and figure it out for themselves.

**Pull request closed without merging**
