### PR TITLE
move cfapps/starter_app_usage to production

### PR DESCRIPTION
**Pull request by zzDRT**
Beth, please review and edit...

### CODE REVIEW

**Comment by jbetht** [comment]
I am out of the office until 02/07/2016.




Note: This is an automated response to your message  "[docs] move
cfapps/starter_app_usage to production (#65)" sent on 2/5/16 7:47:19 PM.

This is the only notification you will receive while this person is away.

**Comment by jbetht** [comment]
I am out of the office until 02/07/2016.




Note: This is an automated response to your message  "Re: [docs] move
cfapps/starter_app_usage to production (#65)" sent on 2/5/16 8:03:38 PM.

This is the only notification you will receive while this person is away.

**Comment by zzDRT** [comment]
Can we merge this now please,  thanks

**Comment by jbetht** [comment]
@zzDRT 
Looks good to me, thanks!

**Pull request merged**
