### PR TITLE
Fix Sydney IP address per support ticket 88673

### PR DESCRIPTION
**Pull request by jbetht**
See https://jazzop27.rtp.raleigh.ibm.com:9443/ccm/web/projects/CloudOE#action=com.ibm.team.workitem.viewWorkItem&id=88673

### CODE REVIEW

**Comment by jbetht** [comment]
@April-yangzsh Please review and merge. When complete, please request prod build and update support ticket RTC to indicate change made. Thanks.

**Comment by April-yangzsh** [comment]
@jbetht Hi Beth, I used the nslookup command to see the IP address of the 3 Bluemix regions, and found out that the results are not what you suggested:
US: 75.126.81.66
London: 5.10.124.141
Sydney: 168.1.35.170

@Crystal4545 will confirm with the dev for further information about how to update this doc, whether to hard code the IP address, or to tell users to use the nslookup command themselves.

**Comment by April-yangzsh** [comment]
FYI - You can open a command prompt, and enter 'nslookup mybluemix.net' to see the IP address of the US-South region. Change the app domain name to see the IP address of other regions.

**Comment by jbetht** [comment]
I updated the RTC work item to ask the originators of the recommendation to comment on what to use and why the IP address they gave does not match what came out of the tool. My preference would be NOT to tell the users to run the command, but to give them the correct IP address. Only if the IP addresses are likely to change would I think we would tell them to run the command.

Please watch the updates to the RTC for how to resolve. Thanks.

**Comment by Crystal4545** [comment]
Per task 88673, comment 16, 17, the update is correct. So merge it and request a prod build to refresh the doc site.  Staging repo content is also updated.

**Pull request merged**
