### PR TITLE
Updated WALLY_SECURITY_TOKEN to WALLY_TOKEN.

### PR DESCRIPTION
**Pull request by chiefkarlin**
Because Dragos told us to.

(He says Hi Janice!)

### CODE REVIEW

**Comment by chiefkarlin** [comment]
Hello - Updating the docs to indicate WALLY_TOKEN.

**Comment by chiefkarlin** [comment]
Hi @janicehamrick  - would you be able to merge in this minor fix?  Working with a customer and want the documentation to accurately reflect the changes they need to make in their environment.

**Comment by janicehamrick** [comment]
Hi @chiefkarlin I'll update and request a production build today. You should see it by tomorrow at the latest.

**Comment by chiefkarlin** [comment]
Thanks Janice - appreciate your assistance!

**Pull request merged**
