### PR TITLE
adding troubleshooting information ts_debug

### PR DESCRIPTION
**Pull request by scmills**

### CODE REVIEW

**Comment by Crystal4545** [comment]
Copy the ts_debug content to staging to verify the look and feel.

**Comment by Crystal4545** [comment]
Add a short description and made some minor changes, then send it for editorial review.

**Comment by scmills** [comment]
Other than a short description, what changes should I make? I verified the content on docs-staging prior to submitting it here. How do I send it for editorial review? I am trying to follow the process here: https://releaseblueprints.ibm.com/display/CLOUDOE/Doc+build+requests+queue

**Comment by jbetht** [comment]
@scmills Crystal was stating that she did add a short description and sent it to me for an editorial review. I signed off on the editorial review.

**Comment by Crystal4545** [comment]
Thanks!
Merge the content and make some minor changes. Then request a prod build to refresh the doc site.

**Pull request merged**
