### PR TITLE
Translation files for BM110ABD103_CD_DOC_Ship

### PR DESCRIPTION
**Pull request by HNorlen**
My very first translation return commit. Please sanity check that I've created my pull request against the right repository. Fingers crossed!

### CODE REVIEW

**Comment by HNorlen** [comment]
Reassigned to Jeff Chi.

**Comment by jeffchi** [comment]
@HNorlen 
I manually moved the nlv files into the expected location before the merge.  The problem is that you didn't package the files from the root directory as RBP instructed.  The correct path in the EN package must be `/services/iotinsights/*md`.

I'll update the NL_MD_CHECKIN build script to abort the build if the path is not correct for the future shipments.

You can go ahead and request a NLV production build.

**Comment by HNorlen** [comment]
@jeffchi @sefuhrer Ah, I see what I did wrong. 

The instructions say:
**IMPORTANT:** make sure you package the files from the root directory of the repo and the CHKPII validation is error-free..  For example, **services\iotrtinsights**.

When packaging I set the root to **services** per the example above which resulted in the file path /iotrtinsights/files... Can we update the instructions with an actual example with a correct, expected, root path as it would appear in TPT? Perhaps a screenshot?

**Comment by HNorlen** [comment]
@jeffchi @sefuhrer One final question. Once I request an NLV production build, my translated documentation goes live, is that correct? I am trying to understand where the DVT fits in all of this?

**Pull request merged**
