### PR TITLE
Add npm pacakge gm for openwhisk

### PR DESCRIPTION
**Pull request by csantanapr**
The npm package gm for GraphicsMagick is available for OpenWhisk

### CODE REVIEW

**Comment by csantanapr** [comment]
@sefuhrer this is safe to deploy as it's already available in production.

**Comment by rabbah** [comment]
@csantanapr you want to take this one also? https://github.com/IBM-Bluemix/docs/issues/134

**Comment by csantanapr** [comment]
@rabbah just did

**Comment by csantanapr** [comment]
@sefuhrer bump
Can we get this merged?

**Pull request merged**
