### PR TITLE
Update pricing page link

### PR DESCRIPTION
**Pull request by vawardibm**
Update to pricing page link to new version

### CODE REVIEW

**Comment by jenschlot** [comment]
@leesakcp Can you make sure the page is using the conref? And make the same change (if needed) in staging...

**Comment by leesakcp** [comment]
@jenschlot sure I'll have a look.

**Comment by leesakcp** [comment]
@jenschlot, can an entry in a dita file be referenced in Markdown?  Or do we add the link to be referenced in the yml file?  The link here is correct, but it's not an entity here, so I'm just trying to figure out how to make it one...

**Comment by jenschlot** [comment]
no, you need to reference the cloudoeconrefs.dita version...

**Comment by leesakcp** [comment]
Edited merge, added coding for pricing page, & then committed.

**Comment by leesakcp** [comment]
This will not work as this addtion in the conref yml file broke the build.  @sefuhrer to meet with me next week (he's out tomorrow) to try to resolve.

**Comment by leesakcp** [comment]
Resolved with @sefuhrer's help.  String goes in parens "" and then it works.  It's in & doesn't break the build.

**Pull request merged**
